apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    uid: EbPG8fYoz
    url: http://jaeger:16686
    jsonData:
#      tracesToMetrics:
#        datasourceUid: 'Prometheus'
#        spanStartTimeShift: '2m'
#        spanEndTimeShift: '-2m'
#        tags: [ { key: 'service.name', value: 'server' }, { key: 'job' } ]
#        queries:
#          - name: 'Request rate'
#            query: 'rate(requests_total($__tags)[5m])'
#          - name: 'Error rate'
#            query: 'rate(errors_total($__tags)[5m])'
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
      nodeGraph:
        enabled: true
      spanBar:
        type: 'None'
  - name: Loki
    type: loki
    uid: EbPG8fYyy
    url: http://loki:3100
    jsonData:
      nodeGraph:
        enabled: true
      spanBar:
        type: 'None'
  - name: Prometheus
    type: prometheus
    uid: EbPG8fYxx
    url: http://prometheus:9090
    jsonData:
      nodeGraph:
        enabled: true