services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "8443:443"
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - shared_volume:/var/www/
    restart: unless-stopped
    networks:
      - caddy
volumes:
  caddy_data: {}
  shared_volume:
    name: shared_volume
networks:
  caddy:
    name: caddy
    driver: bridge