services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
      target: admin_final
    container_name: admin_app
    networks:
      - caddy
    labels:
      caddy: "admin.localdev.me"
      caddy.tls: "internal"
      caddy.root: "* /var/www/admin_app/public"
      caddy.php_fastcgi: "admin_app:9000"
      caddy.php_fastcgi.root: "/var/www/admin_app/public"
      caddy.try_files: "{path} {path}/index.php index.php"
      caddy.file_server:
    volumes:
      - shared_volume:/var/www/shared
      - sqlite_data:/var/www/admin_app/database/sqlite:rw
    develop:
      watch:
        - action: rebuild
          path: ./application
          ignore:
            - ./application/vendor
networks:
  caddy:
    external: true
volumes:
  shared_volume:
    external: true
  sqlite_data:
    driver: local